fixed review comments
UnionInternationalCheminsdeFer/UIC-New-Tariff-Model pull request #64
Opened 2020-10-15 13:15 UTC by nixxus1030

2020-10-15 16:30 UTC, schlpbch requested changes

2020-10-15 16:30 UTC, schlpbch commented on IRS 90918-10 API/openAPI/v2/api/FSM_MVP_Specs.yml
> +        cardValue:
Undos @CGantert345 patch :-(

2020-10-15 16:30 UTC, schlpbch commented on IRS 90918-10 API/openAPI/v2/api/FSM_MVP_Specs.yml
> +                description: MANDATORY - the booking can not be made without reservation, INCLUDED - reservation is included in the offer but is not mandatory, OPTIONAL reservation is not included bu
Undos @schlpbch patch

2020-10-15 18:34 UTC, schlpbch approved these changes

2020-10-15 18:34 UTC, schlpbch commented on IRS 90918-10 API/openAPI/v2/api/FSM_MVP_Specs.yml
> +      integrated reservations or ancillaries
My patch is still not reflected

2020-10-15 18:34 UTC, schlpbch commented on IRS 90918-10 API/openAPI/v2/api/FSM_MVP_Specs.yml
> +        - name: CodeListForMatch
Lowercase please

2020-10-16 09:14 UTC, CGantert345 commented on IRS 90918-10 API/openAPI/v2/api/FSM_MVP_Specs.yml
> +                description: MANDATORY - the booking can not be made without reservation, INCLUDED - reservation is included in the offer but is not mandatory, OPTIONAL reservation is not included bu
What is cardValue?

2020-10-21 10:15 UTC, schlpbch approved these changes
Fine after having carefully merged with @nixxus1030

2020-10-21 10:15 UTC, merged